Licences <- list()
Licences$Digital_Public_Space_Licence <- "http://bbcarchdev.github.io/licences/dps/1.0#id"
Licences$CC0_1.0_Universal_Public_Domain_Dedication <- "http://creativecommons.org/publicdomain/zero/1.0/"
Licences$The_Library_of_Congress_Linked_Data_Service <-"http://id.loc.gov/about/"
Licences$The_MIT_License<-"https://opensource.org/licenses/mit-license.php"
Licences$'Open_Data_Commons_Public_Domain_Dedication_and_License_(PDDL)_v1.0' <- "http://www.opendatacommons.org/licenses/pddl/1.0/"
Licences$No_License <- "https://choosealicense.com/no-permission/"
Licences$European_Union_Public_License_1.1<- "https://spdx.org/licenses/EUPL-1.1.html"
Licences$'EUPL_text_(EUPL-1.2)' <- "https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12"
Licences$Open_Government_Licence_Version_3 <- "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
Licences$Open_Government_Licence_Version_2 <-"http://www.nationalarchives.gov.uk/doc/open-government-licence/version/2/"
Licences$Open_Government_Licence_Version_1<- "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/1/"
Licences$'Attribution_2.0_Generic_(CC_BY_2.0)' <- "https://creativecommons.org/licenses/by/2.0/"
Licences$'Attribution_2.5_Generic_(CC_BY_2.5)' <- "https://creativecommons.org/licenses/by/2.5/"
Licences$'Attribution_3.0_Unported_(CC_BY_3.0)' <-"https://creativecommons.org/licenses/by/3.0/"
Licences$'Attribution_4.0_International_(CC_BY_4.0)' <-"https://creativecommons.org/licenses/by/4.0/"
Licences$'Attribution_4.0_International_(CC_BY_4.0Attribution-ShareAlike_1.0_Generic_(CC_BY-SA_1.0)' <- "https://creativecommons.org/licenses/by-sa/1.0/"
Licences$'Attribution-ShareAlike_2.0_Generic_(CC_BY-SA_2.0)' <-"https://creativecommons.org/licenses/by-sa/2.0/"
Licences$'Attribution-ShareAlike_2.5_Generic_(CC_BY-SA_2.5)' <- "https://creativecommons.org/licenses/by-sa/2.5/"
Licences$'Attribution-ShareAlike_3.0_Unported_(CC_BY-SA_3.0)' <- "https://creativecommons.org/licenses/by-sa/3.0/"
Licences$'Attribution-ShareAlike_4.0_International_(CC_BY-SA_4.0)' <- "https://creativecommons.org/licenses/by-sa/4.0/"
Licences$'Attribution-NoDerivs_1.0_Generic_(CC_BY-ND_1.0)' <- "https://creativecommons.org/licenses/by-nd/1.0/"
Licences$'Attribution-NoDerivs_2.0_Generic_(CC_BY-ND_2.0)' <- "https://creativecommons.org/licenses/by-nd/2.0/"
Licences$'Attribution-NoDerivs_2.5_Generic_(CC_BY-ND_2.5)' <- "https://creativecommons.org/licenses/by-nd/2.5/"
Licences$'Attribution-NoDerivs_3.0_Unported_(CC_BY-ND_3.0)' <- "https://creativecommons.org/licenses/by-nd/3.0/"
Licences$'Attribution-NoDerivatives_4.0_International_(CC_BY-ND_4.0)' <- "https://creativecommons.org/licenses/by-nd/4.0/"
Licences$'Attribution-NonCommercial_1.0_Generic_(CC_BY-NC_1.0)' <- "https://creativecommons.org/licenses/by-nc/1.0/"
Licences$'Attribution-NonCommercial_2.0_Generic_(CC_BY-NC_2.0)' <- "https://creativecommons.org/licenses/by-nc/2.0/"
Licences$'Attribution-NonCommercial_2.5_Generic_(CC_BY-NC_2.5)' <- "https://creativecommons.org/licenses/by-nc/2.5/"
Licences$'Attribution-NonCommercial_3.0_Unported_(CC_BY-NC_3.0)' <- "https://creativecommons.org/licenses/by-nc/3.0/"
Licences$'Attribution-NonCommercial_4.0_International_(CC_BY-NC_4.0)'<- "https://creativecommons.org/licenses/by-nc/4.0/"
Licences$'Attribution-NonCommercial-ShareAlike_1.0_Generic_(CC_BY-NC-SA_1.0)' <- "https://creativecommons.org/licenses/by-nc-sa/1.0/"
Licences$'Attribution-NonCommercial-ShareAlike_2.0_Generic_(CC_BY-NC-SA_2.0)' <- "https://creativecommons.org/licenses/by-nc-sa/2.0/"
Licences$'Attribution-NonCommercial-ShareAlike_2.5_Generic_(CC_BY-NC-SA_2.5)' <- "https://creativecommons.org/licenses/by-nc/2.5/"
Licences$'Attribution-NonCommercial-ShareAlike_3.0_Unported_(CC_BY-NC-SA_3.0)' <- "https://creativecommons.org/licenses/by-nc-sa/3.0/"
Licences$'Attribution-NonCommercial-ShareAlike_4.0_International_(CC_BY-NC-SA_4.0)' <- "https://creativecommons.org/licenses/by-nc-sa/4.0/"
Licences$'Attribution-NoDerivs-NonCommercial_1.0_Generic_(CC_BY-ND-NC_1.0)' <- "https://creativecommons.org/licenses/by-nc-nd/1.0/"
Licences$'Attribution-NonCommercial-NoDerivs_2.0_Generic_(CC_BY-NC-ND_2.0)' <- "https://creativecommons.org/licenses/by-nc-nd/2.0/"
Licences$'Attribution-NonCommercial-NoDerivs_2.5_Generic_(CC_BY-NC-ND_2.5)' <- "https://creativecommons.org/licenses/by-nc-nd/2.5/"
Licences$'Attribution-NonCommercial-NoDerivs_3.0_Unported_(CC_BY-NC-ND_3.0)' <- "https://creativecommons.org/licenses/by-nc-nd/3.0/"
Licences$'Attribution-NonCommercial-NoDerivatives_4.0_International_(CC_BY-NC-ND_4.0)' <- "https://creativecommons.org/licenses/by-nc-nd/4.0/"


